# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f114845f0cdc6be98a0d8f16ca6b0088149efb47fff193d52502fae4bc55592b0a1ac572ee909978ede84d5ac1eddadfe04c1526e2605e881af2210efa1024b0

test:
  secret_key_base: 2cb32914f256adcf5c09562d131ba66d92c347d85a69e3fa782250059acd779b17fb1b48ea2bc26f7436f70480b273743ca1472d41a2a7a4c7cd9d193f9a24a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
