# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b7f8f475053d7445e839c742d23b51950d2731a6ab2567d30684d8d1cf62b33f067dfc4aa605be004da42625a1e31c64142aecc63e8fad62c7724c63f1274b6

test:
  secret_key_base: eb4046570aaa47112ac89187dacfb94d06a057f07c572e8e227c401c6b486fb0ebad97123e1e75131777c878b5e7cc603b125abe35895d1eb749a0f9e96dca54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
