# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8466c4e70ed0d7e61b3f8ca8716abf4070527b19b6d9229630161413039bb47d3521c22e3a07dca549cc0fcf729ba0ea4d64bab3223ef56091e0140969395aa

test:
  secret_key_base: 8623afa6c134c49b2cacecfa7dc4bc1ca833de0f86b7371881bad7355a16fd4324e8a710c94b7e5784b2df666f6751038fb24a208e3fe095ca45c1bd18d55dac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
